version: "2"

run:
  modules-download-mode: vendor

linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - forbidigo
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: The io/ioutil package has been deprecated.
    forbidigo:
      forbid:
        - pattern: ^fmt\.Errorf(# use errors\.Errorf instead)?$
    testifylint:
      disable:
        - empty
        - bool-compare
        - len
        - negative-positive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: stutters
      - linters:
          - revive
        text: var-naming
      - linters:
          - revive
        text: empty-block
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: if-return

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
