#!/usr/bin/env bash

set -eu -o pipefail -x

docker buildx bake --progress=plain mainline buildkit-helper
./hack/lint
./hack/validate-vendor
./hack/install-and-test

docker buildx bake --progress=plain mainline-all buildkit-helper-all