#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

REPO_SLUG=${REPO_SLUG:-tonistiigi/binfmt}
TAG=${TAG:-test}

buildxCmd bake $setFlags --load mainline

set -o pipefail -x
docker run --rm --privileged ${REPO_SLUG}:${TAG} --uninstall qemu-*
status=$(docker run --rm --privileged ${REPO_SLUG}:${TAG} --install all)

echo $status | jq .supported | grep linux/arm64
echo $status | jq .supported | grep linux/amd64
echo $status | jq .supported | grep linux/arm/v7
echo $status | jq .supported | grep linux/arm/v6
echo $status | jq .supported | grep linux/riscv64
echo $status | jq .supported | grep linux/ppc64le
echo $status | jq .supported | grep linux/386

echo $status | jq .emulators | grep qemu-riscv64
echo $status | jq .emulators | grep qemu-arm

docker run --rm arm64v8/alpine uname -a
docker run --rm arm32v7/alpine uname -a
docker run --rm ppc64le/alpine uname -a
docker run --rm s390x/alpine uname -a
docker run --rm i386/alpine uname -a
docker run --rm tonistiigi/debian:riscv uname -a

if [ "$(uname -m)" != "x86_64" ]; then exit 0; fi

status=$(docker run --rm --privileged ${REPO_SLUG}:${TAG} --uninstall aarch64,riscv64)

if echo $status | jq .supported | grep linux/arm64; then exit 1; fi
if echo $status | jq .supported | grep linux/riscv64; then exit 1; fi
echo $status | jq .supported | grep linux/ppc64le
echo $status | jq .supported | grep linux/arm/v7

echo $status | jq .emulators | grep qemu-arm
echo $status | jq .emulators | grep qemu-ppc64le
if echo $status | jq .emulators | grep aarch64; then exit 1; fi
if echo $status | jq .emulators | grep riscv64; then exit 1; fi

if docker run --rm arm64v8/alpine uname -a 2>/dev/null; then exit 1; fi

docker run --rm --privileged ${REPO_SLUG}:${TAG} --install arm64
docker run --rm arm64v8/alpine uname -a

docker run --rm --privileged ${REPO_SLUG}:${TAG} --install riscv64
