#!/usr/bin/env bash

set -eu -o pipefail -x

: ${CONTINUOUS_INTEGRATION=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then progressFlag="--progress=plain"; fi

docker buildx build $progressFlag -f ./hack/dockerfiles/lint.Dockerfile .
