#!/usr/bin/env bash

set -eu -o pipefail -x

: ${CONTINUOUS_INTEGRATION=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then progressFlag="--progress=plain"; fi

output=$(mktemp -d -t buildx-output.XXXXXXXXXX)
docker buildx build $progressFlag \
    --target update \
    -f ./hack/dockerfiles/vendor.Dockerfile \
    -o type=local,dest=$output .
rm -rf ./vendor
cp -R "$output"/* .
rm -rf $output
